openapi: 3.0.3
info:
  title: Vibe Data API
  version: "1.0"
  description: LLM-сервис оптимизации структуры БД и SQL
servers:
  - url: http://{host}
    variables:
      host:
        default: localhost:8080
security:
  - basicAuth: []
paths:
  /new:
    post:
      summary: Запуск задачи анализа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTaskRequest'
            examples:
              sample:
                value:
                  url: "jdbc:trino://trino.example:8080/hive/default?user=xxx&password=yyy"
                  ddl:
                    - statement: "CREATE TABLE cat1.public.t1 (id bigint, ...) ..."
                    - statement: "CREATE TABLE cat1.public.t2 (...) ..."
                  queries:
                    - queryid: "0197a0b2-2284-7af8-9012-fcb21e1a9785"
                      query: "SELECT a.id, b.x FROM cat1.public.t1 a JOIN cat1.public.t2 b ON ..."
                      runquantity: 123
      responses:
        "202":
          description: Принято
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewTaskResponse'
        "400":
          description: Некорректный ввод
        "401":
          description: Нет доступа
  /status:
    get:
      summary: Статус задачи
      parameters:
        - in: query
          name: task_id
          required: true
          schema: { type: string, format: uuid }
      responses:
        "200":
          description: Текущий статус
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /getresult:
    get:
      summary: Получение результата
      parameters:
        - in: query
          name: task_id
          required: true
          schema: { type: string, format: uuid }
      responses:
        "200":
          description: Результат анализа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultResponse'
        "404":
          description: Не найдено
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    DdlStatement:
      type: object
      required: [statement]
      properties:
        statement: { type: string }
    QueryInput:
      type: object
      required: [queryid, query, runquantity]
      properties:
        queryid: { type: string }
        query: { type: string }
        runquantity: { type: integer, minimum: 0 }
    NewTaskRequest:
      type: object
      required: [url, ddl, queries]
      properties:
        url: { type: string, description: "JDBC URL" }
        ddl:
          type: array
          items: { $ref: '#/components/schemas/DdlStatement' }
        queries:
          type: array
          items: { $ref: '#/components/schemas/QueryInput' }
    NewTaskResponse:
      type: object
      properties:
        taskid: { type: string, format: uuid }
    StatusResponse:
      type: object
      properties:
        status:
          type: string
          enum: [RUNNING, DONE, FAILED]
    SqlBlock:
      type: object
      properties:
        statement: { type: string }
    RewrittenQuery:
      type: object
      required: [queryid, query]
      properties:
        queryid: { type: string }
        query: { type: string }
    ResultResponse:
      type: object
      required: [ddl, migrations, queries]
      properties:
        ddl:
          type: array
          items: { $ref: '#/components/schemas/SqlBlock' }
        migrations:
          type: array
          items: { $ref: '#/components/schemas/SqlBlock' }
        queries:
          type: array
          items: { $ref: '#/components/schemas/RewrittenQuery' }